### ISSUE TITLE
Vite dev server fails with bareModules enabled/configured

### ISSUE THREAD

**Issue by spinturnix** [slavafyi/vite-plugin-shopify-import-maps#11]
Hey @slavamak,

My dev server is failing to start with a TypeError that `plugins` is undefined when trying to call `.find()` on it in the `buildStart()` method. This only occurs for `dev` with `bareModules` enabled, while `build` runs perfectly.

Here's the error:
```
error when starting dev server:
TypeError: Cannot read properties of undefined (reading 'find')
    at Context.buildStart (__PROJECT_PATH__/node_modules/vite-plugin-shopify-import-maps/dist/index.js:101:43)
    at hookParallel (__PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63251:47)
    at Object.buildStart (__PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:63606:37)
    at __PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:60305:29
    at initServer (__PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:60313:11)
    at httpServer.listen (__PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:60323:23)
    at __PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:48622:20 
    at new Promise (<anonymous>)
    at httpServerStart (__PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:48604:12)
    at startServer (__PROJECT_PATH__/node_modules/vite/dist/node/chunks/dep-R0I0XnyH.js:60355:30)
```

And here's my config:
```
import { defineConfig } from 'vite'
import shopify from 'vite-plugin-shopify'
import importMaps from 'vite-plugin-shopify-import-maps'

export default defineConfig({
  build: {
    emptyOutDir: false,
    rollupOptions: {
      output: {
        entryFileNames: '[name].bundle.min.js',
        chunkFileNames: '[name].chunk.min.js',
        assetFileNames: '[name].min[extname]',
      }
    }
  },
  plugins: [
    shopify({
      themeRoot: 'theme',
      sourceCodeDir: 'src',
      entrypointsDir: 'src/entries',
      additionalEntrypoints: [
        'src/scripts/components/*.js',
        'node_modules/@11ty/is-land/is-land.js',
      ]
    }),
    importMaps({ 
      themeRoot: 'theme',
      bareModules: {
        groups: {
          components: 'src/scripts/components',
          modules: 'node_modules',
        }
      }
    })
  ]
})
```

**Comment by slavafyi** [comment]
Hi @spinturnix, thanks for the catch! I'll investigate the issue later today to understand why it's occurring.

**Comment by slavafyi** [comment]
@spinturnix please update `vite-plugin-shopify-import-maps` to version `0.4.2` or latest. This should work ok now. Let me know, thanks

**Comment by spinturnix** [comment]
Hey @slavamak, Thanks for the quick response, the dev server is now running!

However, now I see `importmap.liquid` is being wiped and all scripts referenced in the importmap will not resolve. Is there a reason you're clearing the file?

**Comment by slavafyi** [comment]
> Hey @slavamak, Thanks for the quick response, the dev server is now running!
> 
> However, now I see `importmap.liquid` is being wiped and all scripts referenced in the importmap will not resolve. Is there a reason you're clearing the file?

Well yeah. In dev mode we don't need import-maps because vite dev server takes care of it. You can also see here #3 about why the `importmap` file is being cleared. Although we don't use the `<base>` tag anymore, so maybe it's not necessary, not sure

**Comment by spinturnix** [comment]
Thanks for the context. I see the reasoning there, but I'm only using the `vite-tag` in `theme.liquid` and main template files. The rest of my sections and most components are using imports like:
```
<script type="module">
  import 'components/component-name'
</script>
```

It would be cool if vite-tag could render imports like this, or if your importmap adjusted the URLs for dev, as mentioned in #3.

As a workaround, I could probably add a watch function to my `src/components/*.js` and move them to `theme/assets` on save. Then let the Shopify CLI sync and refresh.

**Comment by slavafyi** [comment]
> Thanks for the context. I see the reasoning there, but I'm only using the `vite-tag` in `theme.liquid` and main template files. The rest of my sections and most components are using imports like:
> 
> ```
> <script type="module">
>   import 'components/component-name'
> </script>
> ```
> 
> It would be cool if vite-tag could render imports like this, or if your importmap adjusted the URLs for dev, as mentioned in #3.
> 
> As a workaround, I could probably add a watch function to my `src/components/*.js` and move them to `theme/assets` on save. Then let the Shopify CLI sync and refresh.

Yeah, I thought about it, but then I don't see the point of using vite dev server. In fact, I use it the way you described, but only without the `shopify-vite` plugin. Only plugin for import-map and @11ty/is-land

**Comment by slavafyi** [comment]
Maybe I'll think about it again. If you have any ideas, you can open a new issue to discuss it :)
