### ISSUE TITLE
CSS entrypoints are added to importmap as JS assets

### ISSUE THREAD

**Issue by spinturnix** [slavafyi/vite-plugin-shopify-import-maps#12]
Hey @slavamak,

I have some templates and sections with separate stylesheets. I still want these styles processed by Vite and postcss so I've included them in `additionalEntrypoints`.

However, I've just noticed these "styles" are now appearing inside `importmap.liquid` as `js` files.

Is there any way to ignore any non-js files in the importmap plugin? I have some workarounds in mind, but would be nicer if this just worked haha...

Let me know, thanks!

**Comment by slavafyi** [comment]
Hi @spinturnix! Yes, it makes sense. Probably I missed it.. I'll fix it today. Thanks
