### ISSUE TITLE
Shopify CLI doesn't allow empty files

### ISSUE THREAD

**Issue by bernier** [slavafyi/vite-plugin-shopify-import-maps#17]
This Vite plugin automatically creates an empty snippet importmap.liquid
When running the Shopify CLI v 3.71.3, I'm getting the following error:

_Failed to perform the initial theme synchronization.
Asset must have a value or attachment_ 

The Shopify CLI crashes.

I disabled this plugin so that I could continue working on my project. 

See the ticket https://github.com/Shopify/cli/issues/5010

**Comment by slavafyi** [comment]
Thanks for the report on this, I will check it out as soon as possible!

**Comment by jamesmengo** [comment]
@slavamak FYI, This has been patched on the Shopify CLI side to allow empty files. Hope that helps!

**Comment by slavafyi** [comment]
@jamesmengo thank you! Yeah, in my end it works fine with version [3.71.4](https://www.npmjs.com/package/@shopify/cli/v/3.71.4). @bernier could you confirm this?

**Comment by bernier** [comment]
@slavamak yes it works now. Thanks
