### ISSUE TITLE
<base> tag - Dev hot-reload conflict

### ISSUE THREAD

**Issue by jonathanmoore** [slavafyi/vite-plugin-shopify-import-maps#3]
After building the snippet/importmap.liquid is first created and everything works as expected.  However during development the base tag `<base href="//store-name.myshopify.com/cdn/shop/t/109/assets/">` is causing the code that the Shopify CLI injects for Hot Reload to connect to //store-name.myshopify.com/hot-reload instead of 127.0.0.1:9292/hot-reload.

It would be helpful if during dev `vite` either base URL is correctly set to 127.0.0.1:9292 or even if the importmap.liquid file was emptied.

**Comment by slavafyi** [comment]
@jonathanmoore Thanks for the catch, you're right. I think it would be better if the importmap file is just cleaned up during dev, because it's not necessary, vite will do everything for us. I'll check it tomorrow :)
